### ISSUE TITLE
Little example

### ISSUE THREAD

**Issue by Giancarlo1974** [georgebarwood/RustDB#2]
Hi I'm a Rust newbie
Your work looks very promising
I've looked the rustweb example, but it's still too complicated for my current level

Could you write a small example that performs a CREATE, INSERT and SELECT?

`CREATE TABLE dbo.Persons (
    PersonID int,
    LastName string(255),
    FirstName string(255),
    Address string(255),
    Country string(255)
)

INSERT INTO dbo.Persons (PersonID, LastName, FirstName, Address, Country)
VALUES (1, 'Alb', 'Gian', 'street 1', 'ITA')

INSERT INTO dbo.Persons (PersonID, LastName, FirstName, Address, Country)
VALUES (2, 'Alb', 'Sim', 'street 2', 'ITA')

SELECT PersonID, LastName, FirstName, Address, Country FROM dbo.Persons`

How can I implement a loop to read the data extracted from the query?

**Comment by georgebarwood** [comment]
Giancarlo, Thanks for your interest. As described here: https://docs.rs/rustdb/latest/rustdb/“The method Database::run (or alternatively Database::run_timed) is called to execute an SQL query. This takes a Transaction parameter which accumulates SELECT results ...” Transaction is a trait, but there is a standard implementation GenTransaction. which accumulates query results in an output buffer.It may help to look at the example program:https://github.com/georgebarwood/rustweb Kind regards,GeorgeMobile: 0796 864 2765Email: ***@***.*** From: Giancarlo1974Sent: 28 August 2022 00:14To: georgebarwood/RustDBCc: SubscribedSubject: [georgebarwood/RustDB] Little example (Issue #2) Hi I'm a Rust newbieYour work looks very promisingI've looked the rustweb example, but it's still too complicated for my current levelCould you write a small example that performs a CREATE, INSERT and SELECT?`CREATE TABLE dbo.Persons (PersonID int,LastName string(255),FirstName string(255),Address string(255),Country string(255))INSERT INTO dbo.Persons (PersonID, LastName, FirstName, Address, Country)VALUES (1, 'Alb', 'Gian', 'street 1', 'ITA')INSERT INTO dbo.Persons (PersonID, LastName, FirstName, Address, Country)VALUES (2, 'Alb', 'Sim', 'street 2', 'ITA')SELECT PersonID, LastName, FirstName, Address, Country FROM dbo.Persons`How can I implement a loop to read the data extracted from the query?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by Giancarlo1974** [comment]
In the meantime, thanks for answering me
I tried to make a mini example, inspired by your example

[Here what I wrote](https://github.com/Giancarlo1974/RustDB_example/blob/master/src/main.rs)

https://github.com/Giancarlo1974/RustDB_example/blob/master/src/main.rs

In the meantime, thanks for answering me
I tried to make a mini example, inspired by your example

Here what I wrote:

https://github.com/Giancarlo1974/RustDB_example/blob/master/src/main.rs

But I'm doing something wrong on line 33

`Hello, world!
Init db
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/gianca/.cargo/registry/src/github.com-1ecc6299db9ec823/rustdb-2.10.0/src/sys.rs:290:38
stack backtrace:
   0:     0x55a6d65a1aad - std::backtrace_rs::backtrace::libunwind::trace::h8217d0a8f3fd2f41
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55a6d65a1aad - std::backtrace_rs::backtrace::trace_unsynchronized::h308103876b3af410
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55a6d65a1aad - std::sys_common::backtrace::_print_fmt::hc208018c6153605e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55a6d65a1aad - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf89a7ed694dfb585
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55a6d65c01fc - core::fmt::write::h21038c1382fe4264
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
   5:     0x55a6d659fb51 - std::io::Write::write_fmt::h7dbb1c9a3c254aef
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
   6:     0x55a6d65a3135 - std::sys_common::backtrace::_print::h4e8889719c9ddeb8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55a6d65a3135 - std::sys_common::backtrace::print::h1506fe2cb3022667
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55a6d65a3135 - std::panicking::default_hook::{{closure}}::hd9d7ce2a8a782440
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
   9:     0x55a6d65a2e56 - std::panicking::default_hook::h5b16ec25444b1b5d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:314:9
  10:     0x55a6d65a36c6 - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:698:17
  11:     0x55a6d65a3579 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:586:13
  12:     0x55a6d65a1f64 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55a6d65a32e9 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
  14:     0x55a6d642d893 - core::panicking::panic_fmt::h1de71520faaa17d3
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
  15:     0x55a6d642d75d - core::panicking::panic::h467ee1bf554babeb
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
  16:     0x55a6d64d0461 - core::option::Option<T>::unwrap::h810bf78f1148a59e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/option.rs:775:21
  17:     0x55a6d646d947 - rustdb::sys::get_id_gen::he1e666a80684feb5
                               at /home/gianca/.cargo/registry/src/github.com-1ecc6299db9ec823/rustdb-2.10.0/src/sys.rs:290:21
  18:     0x55a6d64c79fa - rustdb::Database::new::h5463dda4f4f8e781
                               at /home/gianca/.cargo/registry/src/github.com-1ecc6299db9ec823/rustdb-2.10.0/src/lib.rs:352:30
  19:     0x55a6d642efdf - hello_cargo::main::hf291af9d4d7e7b78
                               at /home/gianca/progetti/rust/hello_cargo/src/main.rs:33:14
  20:     0x55a6d642e04b - core::ops::function::FnOnce::call_once::h07eb7ec61bbaf70c
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5
  21:     0x55a6d642fefe - std::sys_common::backtrace::__rust_begin_short_backtrace::hdf7b967f71fe92cc
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:122:18
  22:     0x55a6d642dff1 - std::rt::lang_start::{{closure}}::h9a4ec90828c9e6ee
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:145:18
  23:     0x55a6d659cbfe - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h4937aaa125c8d4b2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:280:13
  24:     0x55a6d659cbfe - std::panicking::try::do_call::h6f5c70e8b0a34f92
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  25:     0x55a6d659cbfe - std::panicking::try::h68766ba264ecf2e2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  26:     0x55a6d659cbfe - std::panic::catch_unwind::hc36033d2f9cc04af
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  27:     0x55a6d659cbfe - std::rt::lang_start_internal::{{closure}}::h78c037f4a1a28ded
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:128:48
  28:     0x55a6d659cbfe - std::panicking::try::do_call::he6e1fffda4c750ee
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  29:     0x55a6d659cbfe - std::panicking::try::h48a77ddbb2f4c87a
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  30:     0x55a6d659cbfe - std::panic::catch_unwind::hfa809b06a550a9e7
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  31:     0x55a6d659cbfe - std::rt::lang_start_internal::h4db69ed48eaca005
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:128:20
  32:     0x55a6d642dfc0 - std::rt::lang_start::h4373514a146c60cc
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:144:17
  33:     0x55a6d642f33c - main
  34:     0x7f95ae8d7083 - __libc_start_main
  35:     0x55a6d642db8e - _start
  36:                0x0 - <unknown>`


Can you help me ?

**Comment by Giancarlo1974** [comment]
please

**Comment by georgebarwood** [comment]
Hi, I did reply earlier by email. Not sure how that works.

When I change the  line to this:
 
let a: String = "SELECT Id, LastName, FirstName FROM dbo.Cust".to_owned();
 
The program runs without any error.

**Comment by georgebarwood** [comment]
Hi, When I ran your program I got this error: Hello, world!Init dbHello, db!thread 'main' panicked at 'table [dbo].[Persons] not found',...Run error table [dbo].[Persons] not found in batch at line 1 column 72.End! Because the table is named “Person” not “Persons”. Note: you probably don’t want to run with RUST_BACKTRACE turned on.The panic was handled, but all that tracing obscures the output.

**Comment by georgebarwood** [comment]
When I change the  line to this: let a: String = "SELECT Id, LastName, FirstName FROM dbo.Cust".to_owned(); The program runs without any error. Note: the output data will be in x ( as bytes ). You could do a println! to see that.

**Comment by Giancarlo1974** [comment]
It would be great if you wrote a very small example:

- one file
- how to create a table
- how to insert a record
- how to look for it
- how to view it
